
- name: Check if JumpCloud is already installed
  shell: "[ -d /opt/jc ] && echo 'Found' || echo ''"
  register: jc_installed
  when: package_install

- name: Update time
  shell: "ntpdate -u pool.ntp.org"
  when: "not jc_installed.stdout"

- include: install.yml
  when: package_install

- name: Clean up agent info
  file: path="{{ item }}" state=absent
  with_items:
    - "/opt/jc/ca.crt"
    - "/opt/jc/client.crt"
    - "/opt/jc/client.key"
    - "/opt/jc/jcagent.conf"
  when: not configure_agent

- name: Restart JumpCloud Agent
  service: name=jcagent state=restarted
  when: configure_agent

- name: Copy tagging script
  template: src=tag_node.rb.j2 dest=/tmp/tag_node.rb
  when: configure_agent

- name: Tag server in JumpCloud
  command: ruby /tmp/tag_node.rb
  retries: 5
  delay: 10
  when: configure_agent

