---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"

  pre_tasks:
    - name: Include Amazon EC2 variables
      include_vars: "cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
      no_log: yes
      when: cloud_provider == "ec2"
    - debug: msg=" slave types {{slave_types}}"

  roles:
    - role: ansible-terraform


