---
- hosts: localhost
  connection: local
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"

  pre_tasks:
    - name: Include Amazon EC2 variables
      include_vars: "cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
      when: cloud_provider == "ec2"

  roles:
    - role: ansible-terraform


