---
- hosts: localhost
  connection: local
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    # Create a VPC
    - role: ec2Vpc
      when: "cloud_provider == 'ec2' and aws_all_security_group_id is not defined"

    # Boot the NFS server node
    - role: ec2Boot
      count: 1
      node_class: "{{service_class_name}}"
      node_group_name: "{{ inventory_group_service }}"
      when: cloud_provider == 'ec2'

  post_tasks:
    - name: wait for service nodes to be available
      local_action: wait_for host="{{ item.public_ip_address }}" port=22 delay=60 timeout=320 state=started
      with_items: service_instances
      when: cloud_provider == 'ec2' and service_instances is defined

    - name: Add data volume
      ec2_vol:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ ec2_region }}"
        zone: "{{ ec2_zone }}"
        device_name: "/dev/xvdf"
        volume_type: "{{ data_vol_type }}"
        volume_size: "{{ data_vol_size_gb }}"
        instance: "{{ hostvars[groups[inventory_group_service][0]]['ec2_id'] }}"
        state: present
      when: cloud_provider == "ec2"

- include: service_deploy_playbook.yml