---
- hosts: localhost
  gather_facts: no
  vars_files:
    - playbook_vars/common.yml
    - playbook_vars/required_vars.yml
    - playbook_vars/aws_secret_vars.yml
  roles:
    # Ensure a VPC exists
    - role: ec2Vpc
      when: aws_master_security_group_id is not defined

    # Boot the slaves
    - role: ec2Boot
      count: "{{ slave_count }}"
      node_class: "{{ slave_class_name }}"
      node_group_name: "{{ inventory_group_slave }}"

  post_tasks:
    - name: wait for slave nodes to be available
      local_action: wait_for host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      with_items: slave_instances
      when: slave_instances is defined

- include: slave_deploy_playbook.yml