---
- include: playbooks/ec2_master_create.yml
  when: cloud_provider == "ec2"

- hosts: localhost
  gather_facts: no
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  tasks:
    - name: wait for slave nodes to be available
      local_action: wait_for host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      with_items: slave_instances
      when: slave_instances is defined and cloud_provider == "ec2"

- include: slave_deploy_playbook.yml