---
- hosts: localhost
  connection: local
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    - role: ../roles/ansible-cloud-inventory-parse
      provider: "{{ cloud_provider }}"

- hosts: [ "{{ inventory_group_service }}", "{{ inventory_group_master }}","{{ inventory_group_slave }}" ]
  remote_user: "{{ management_user }}"
  become: yes
  vars_files:
    - "cluster_vars/common.yml"
    - "cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "cluster_vars/{{ cluster_name }}/users.yml"
  pre_tasks:
    - name: Add ssh keys to management user
      authorized_key: key="{{ item }}" state=present user=ubuntu exclusive=no
      with_items: "{{ additional_ssh_keys }}"
      when: additional_ssh_keys is defined

  roles:
    - role: ansible-welder-user
      group: "welder"
      user_list: "{{ welder_user_list }}"
      dataDir: "{{ data_mount_point }}"