- name: Install Ansible repo
  shell: "pip install ansible==1.9.4"

- name: Install git and zip
  apt: name="{{ item }}" state=present
  with_items:
    - git
    - zip

- name: Make working directory
  file: path="{{ ansible_scaler_dir }}" state=directory owner="{{ management_user }}"

- name: Fetch Ansible scripts
  git:
    dest: "{{ ansible_scaler_dir }}"
    repo: https://github.com/appsoma/ansible-appsoma-mesos.git
    version: "{{ ansible_scaler_version if ansible_scaler_version is defined else 'HEAD' }}"
    update: yes
    force: yes
  sudo: yes
  sudo_user: "{{ management_user }}"
  register: git_pull

- name: Copy Terraform executables
  copy: src="{{ root_dir }}terraform_{{ terraform_version }}/{{ item }}" dest="/usr/local/bin/{{ item }}" owner="{{ management_user }}" mode=0777
  with_items: terraform_executables
  when: is_scaler_host

- name: Make Ansible cluster variable dir
  file: path="{{ ansible_scaler_dir }}/cluster_vars/{{ cluster_name }}" state=directory owner="{{ management_user }}"

- name: Add Ansible variable files
  copy:
    src: "{{ root_dir }}cluster_vars/{{ cluster_name }}/{{ item }}"
    dest: "{{ ansible_scaler_dir }}/cluster_vars/{{ cluster_name }}/{{ item }}"
    owner: "{{ management_user }}"
    mode: 0600
  with_items:
    - aws_secret_vars.yml
    - required_vars.yml
    - "{{ cluster_name }}_key.pem"
    - users.yml
  when: is_scaler_host

