- debug: msg="WELDER"

- name: Create Welder directory
  file: path=/opt/welder state=directory

- name: Fetch Welder container setup script
  get_url: 
    url: https://github.com/appsoma/welder/blob/master/scripts/welder_in_container.bash
    dest: /opt/welder/welder_in_container.bash

- name: create Welder config
  template: src=welder_container_config.j2 dest=/opt/welder/welder_container_config
  register: config_create

- name: stop Welder in Docker
  shell: "cd /opt/welder; sudo ./welder_in_container.bash --stop"
  when: config_create.changed or git_pull.changed

- name: start Welder in Docker
  shell: "cd /opt/welder; sudo ./welder_in_container.bash --start --no-questions"