- name: Create DB directory
  file: path="{{db_folder}}" state=directory owner="{{ management_user }}"

- name: Create Mongo marathon run script
  template: src="run_mongo.sh.j2" dest="{{ welder_data_dir }}/run_mongo.sh" mode=0755

- name: Run Mongo in marathon
  shell: "{{ welder_data_dir }}/run_mongo.sh start"



