- name: Create Yak dir
  file: path="{{ welder_data_dir }}/yak" state=directory owner="{{ management_user }}" group="{{ welder_group['name'] }}" mode=2775

- name: Clone Yak source
  git:
    dest: "{{ welder_data_dir }}/yak"
    repo: https://github.com/appsoma/welder_support.git
    version: "{{ welder_support_version if welder_support_version is defined else 'HEAD' }}"
    update: yes
    force: yes
  sudo: yes
  sudo_user: "{{ management_user }}"
  notify: Stop wsyak
  notify: Start wsyak

- name: Run NPM for wsyak
  shell: "cd {{  welder_data_dir }}/yak/wsyak; npm install;"
  sudo: yes
  sudo_user: "{{ management_user }}"
  register: npmwsyak
  failed_when: npmwsyak.stderr.find('ERROR') != -1
  changed_when: npmwsyak.stdout != ''
  notify: Stop wsyak
  notify: Start wsyak
  when: yak_mode == 'wsyak'

#- name: Create KaYak dir
#  file: path="{{ data_mount_point }}/kayak" state=directory owner="{{ management_user }}" group="{{ management_user }}"

#- name: Clone KaYak source
#  git:
#    dest: "{{ data_mount_point }}/kayak"
#    repo: https://github.com/appsoma/kayak.git
#    version: "{{ kayak_version if kayak_version is defined else 'HEAD' }}"
#    update: yes
#    force: yes
#  sudo: yes
#  sudo_user: "{{ management_user }}"