- name: Get uname
  command: uname -r
  register: os_uname
  changed_when: False

- name: Add specific key
  apt_key: keyserver="{{docker_repo_keyserver}}" id="{{docker_repo_key}}" state=present
  when: package_install

- name: Add docker repo
  apt_repository: repo="deb {{docker_repo}} ubuntu-trusty main" update_cache=yes state=present
  when: package_install

- name: Install os packages
  apt: pkg={{item}} state=present
  with_items: 
    - "linux-image-extra-{{os_uname.stdout}}"
    - "docker-engine"
  notify: Restart Docker
  when: package_install

- name: Docker default config file
  template: src=docker-defaults.j2 dest=/etc/default/docker
  notify: Restart Docker

- name: Change ufw forward policy to ACCEPT
  command: sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
  when: docker_listen_tcp == True
  notify: Restart Docker

- name: Reload ufw
  command: ufw reload
  when: docker_listen_tcp == True

- name: Allow incoming tcp traffic on {{docker_listen_port}}
  command: ufw allow {{docker_listen_port}}/tcp
  when: docker_listen_tcp == True

- name: Start and enable Docker
  service: name=docker state=started enabled=yes