- name: Add docker registry dir
  file: path="{{ docker_registry_dir }}" state=directory owner=root group=root mode=0700

- name: Add docker registry config
  template: src=docker_registry_config.yml.j2 dest="{{ docker_registry_dir }}/docker_registry_config.yml" owner=root group=root mode=0600

- name: Add docker registry Run script
  template: src=run_docker_registry.sh.j2 dest="{{ docker_registry_dir }}/run_docker_registry.sh" mode=0700