---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: install_registry.yml
  when: hostvars[inventory_hostname].private_ip_address is defined and registry_host == hostvars[inventory_hostname].private_ip_address

