---
- include: Debian.yml
  when: ansible_os_family == "Debian" and not (install_registry is defined and install_registry)

- include: install_registry.yml
  when: install_registry is defined and install_registry

