- name: Install Erlang repo key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present

- name: Install Erlang repo
  apt_repository: repo="deb http://packages.erlang-solutions.com/debian wheezy contrib" state=present

- name: Install Erlang
  apt: pkg=erlang state=present update_cache=yes

- name: Install RabbitMQ repo key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Install RabbitMQ repo
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main" state=present

- name: Install RabbitMQ
  apt: pkg=rabbitmq-server state=present update_cache=yes

- name: Start RabbitMQ
  service: name=rabbitmq-server state=started enabled=yes

- name: Add Sensu vhost to RabbitMQ
  command: rabbitmqctl add_vhost /sensu
  register: rabbit_vhost
  changed_when: rabbit_vhost.stderr == ""
  failed_when: rabbit_vhost.stderr != "" and rabbit_vhost.stderr.find('vhost_already_exists') == -1

- name: Add Sensu user to RabbitMQ
  command: rabbitmqctl add_user sensu secret
  register: rabbit_user
  changed_when: rabbit_user.stderr == ""
  failed_when: rabbit_user.stderr != "" and rabbit_user.stderr.find('user_already_exists') == -1

- name: Set Sensu user permissions in RabbitMQ
  command: rabbitmqctl set_permissions -p /sensu sensu '".*"' '".*"' '".*"'