- name: Create Uchiwa config directory
  file: path="{{ uchiwa_dir }}" state=directory owner="{{ management_user }}"

- name: Create Uchiwa config
  template: src=uchiwa_config.json.j2 dest="{{ uchiwa_dir }}/config.json" owner="{{ management_user }}"

- name: Start Uchiwa in docker
  shell: "{{ uchiwa_docker_cmd }}"
  register: start_local_docker
  changed_when: start_local_docker.stderr == "" or start_local_docker.stderr.find('already in use') == -1
  failed_when: start_local_docker.stderr != "" and start_local_docker.stderr.find('already in use') == -1 and start_local_docker.stderr.find('Downloaded newer image') == -1

#- name: Create Uchiwa Marathon JSON
#  template: src=uchiwa_marathon.json.j2 dest="{{ uchiwa_dir }}/uchiwa_marathon.json" owner="{{ management_user }}"

#- name: Create Uchiwa Marathon script
#  template: src=uchiwa_marathon.sh.j2 dest="{{ uchiwa_dir }}/uchiwa_marathon.sh" owner="{{ management_user }}" mode=0744

#- name: Start Uchiwa in Marathon
#  command: "{{ uchiwa_dir }}/uchiwa_marathon.sh start"
