- debug: msg="Node group is {{ node_group_name }}"

- set_fact: max_id_name=""
- set_fact: start_id=0
- set_fact: max_id_name="{{ groups[node_group_name] | sort('ec2_tag_id' | int) | first }}"
  when: node_group_name in groups

- set_fact: start_id="{{ hostvars[max_id_name]['ec2_tag_id'] | int + 1}}"
  when: max_id_name is defined and max_id_name != ""

- name: Report max ID
  debug: msg="Node with the max ID for {{ node_group_name }} is {{ max_id_name }}, ID {{ hostvars[max_id_name]['ec2_tag_id'] }}, next node should be ID {{ start_id }}"
  when: node_group_name in groups