registry_host: ''
docker_registry_dir: "{{ data_mount_point }}/docker_registry"
docker_registry_command: "docker run -d --name docker-registry --restart=always -p 5000:5000 -v {{ docker_registry_dir }}/docker_registry_config.yml:/etc/docker/registry/config.yml registry:2"
