- name: fetch Rhino from github
  git:
    dest: "{{ rhino_dir }}"
    repo: https://github.com/appsoma/rhino.git
    version: "{{ rhino_version if rhino_version is defined else 'HEAD' }}"
    update: yes

- name: start Rhino in marathon
  shell: "./rhino_marathon.sh start"
  args:
    chdir: "{{ rhino_dir }}"


