#- name: fetch Rhino from github
#  git:
#    dest: /opt/rhino
#    repo: https://github.com/appsoma/rhino.git
#    version: HEAD
#    update: no
#  register: git_pull

- name: Create Rhino directory
  file: path=/opt/rhino state=directory

- name: Fetch Rhino container setup script
  get_url:
    url: https://github.com/appsoma/rhino/blob/master/rhino_in_container.bash
    dest: /opt/rhino/rhino_in_container.bash

- name: create Rhino config
  template: src=rhino_container_config.j2 dest=/opt/rhino/rhino_container_config
  register: config_create

- name: stop Rhino in Docker
  shell: "cd /opt/rhino; sudo ./rhino_in_container.bash --stop"
  when: config_create.changed or git_pull.changed

- name: start Rhino in Docker
  shell: "cd /opt/rhino; sudo ./rhino_in_container.bash --start --no-questions"

