- name: Service nodes on Amazon EC2
  debug: msg="{{ groups[provider_group_prefix[provider] + inventory_group_service] }}"
  when: groups[provider_group_prefix[provider] + inventory_group_service] is defined

- name: Masters on Amazon EC2
  debug: msg="{{ groups[provider_group_prefix[provider] + inventory_group_master] }}"
  when: groups[provider_group_prefix[provider] + inventory_group_master] is defined

- name: Slaves on Amazon EC2
  debug: msg="{{ groups[provider_group_prefix[provider] + inventory_group_slave] }}"
  when: groups[provider_group_prefix[provider] + inventory_group_slave] is defined

- name: Add service node variables to host list
  add_host:
    hostname: "{{ item }}"
    groupname: "{{ inventory_group_service }}"
    system_name: "{{ hostvars[item].tags.Name }}"
    short_name: "{{ hostvars[item].tags.short_name }}"
    type: "{{ hostvars[item].tags.type }}"
    id: "{{ hostvars[item].tags.id }}"
    public_ip_address: "{{ hostvars[item].public.ip }}"
    public_dns_name: "{{ hostvars[item].public.dns }}"
    private_ip_address: "{{ hostvars[item].private.ip }}"
    private_dns_name: "{{ hostvars[item].private.ip }}"
  with_items: "{{ groups[provider_group_prefix[provider] + inventory_group_service] | default([]) }}"
  when: groups[provider_group_prefix[provider] + inventory_group_service] is defined

- name: Add master node variables to host list
  add_host:
    hostname: "{{ item }}"
    groupname: "{{ inventory_group_master }}"
    system_name: "{{ hostvars[item].tags.Name }}"
    short_name: "{{ hostvars[item].tags.short_name }}"
    type: "{{ hostvars[item].tags.type }}"
    id: "{{ hostvars[item].tags.id }}"
    zoo_id: "{{ hostvars[item].tags.zoo_id }}"
    public_ip_address: "{{ hostvars[item].public.ip }}"
    public_dns_name: "{{ hostvars[item].public.dns }}"
    private_ip_address: "{{ hostvars[item].private.ip}}"
    private_dns_name: "{{ hostvars[item].private.dns}}"
  with_items: "{{ groups[provider_group_prefix[provider] + inventory_group_master] | default([]) }}"
  when: groups[provider_group_prefix[provider] + inventory_group_master] is defined

- name: Add slave node variables to host list
  add_host:
    hostname: "{{ item }}"
    groupname: "{{ inventory_group_slave }}"
    system_name: "{{ hostvars[item].tags.Name }}"
    short_name: "{{ hostvars[item].tags.short_name }}"
    type: "{{ hostvars[item].tags.type }}"
    id: "{{ hostvars[item].tags.id }}"
    public_ip_address: "{{ hostvars[item].public.ip }}"
    public_dns_name: "{{ hostvars[item].public.dns }}"
    private_ip_address: "{{ hostvars[item].private.ip }}"
    private_dns_name: "{{ hostvars[item].private.ip }}"
  with_items: "{{ groups[provider_group_prefix[provider] + inventory_group_slave] | default([]) }}"
  when: groups[provider_group_prefix[provider] + inventory_group_slave] is defined
  when: groups[provider_group_prefix[provider] + inventory_group_slave] is defined