
- name: Show Service Nodes in groups
  debug: msg="service nodes {{ groups[inventory_group_service] }}"
  when: groups[inventory_group_service] is defined

- name: Show Master Nodes in groups
  debug: msg="master nodes {{ groups[inventory_group_master] }} "
  when: groups[inventory_group_master] is defined

- name: Show Slave Nodes in groups
  debug: msg="slave nodes {{ groups[inventory_group_slave] }}"
  when: groups[inventory_group_slave] is defined
- include: none.yml
  when: provider == 'none'

- include: gce.yml
  when: provider == 'gce'

- include: ec2.yml
  when: provider == 'ec2'