- name: Change values for existing Ubuntu inventory
  debug: msg="No action needed!"

- name: Check service node variables host variables
  add_host:
    hostname: "{{ hostvars[item]['public_ip_address'] }}"
    groupname: "{{ inventory_group_service }}"
    system_name: "{{ hostvars[item]['system_name'] }}"
    id: "{{ hostvars[item]['id'] }}"
    public_ip_address: "{{ hostvars[item]['public_ip_address'] }}"
    public_dns_name: "{{ hostvars[item]['public_dns_name'] }}"
    private_ip_address: "{{ hostvars[item]['private_ip_address'] }}"
    private_dns_name: "{{ hostvars[item]['private_dns_name'] }}"
  with_items: groups[inventory_group_service]

- name: Add master node variables to host list
  add_host:
    hostname: "{{ hostvars[item]['public_ip_address'] }}"
    groupname: "{{ inventory_group_master }}"
    system_name: "{{ hostvars[item]['system_name'] }}"
    id: "{{ hostvars[item]['id'] }}"
    zoo_id: "{{ hostvars[item]['zoo_id'] }}"
    public_ip_address: "{{ hostvars[item]['public_ip_address'] }}"
    public_dns_name: "{{ hostvars[item]['public_dns_name'] }}"
    private_ip_address: "{{ hostvars[item]['private_ip_address'] }}"
    private_dns_name: "{{ hostvars[item]['private_dns_name'] }}"
  with_items: groups[inventory_group_master]

- name: Add slave node variables to host list
  add_host:
    hostname: "{{ hostvars[item]['public_ip_address'] }}"
    groupname: "{{ inventory_group_slave }}"
    system_name: "{{ hostvars[item]['system_name'] }}"
    id: "{{ hostvars[item]['id'] }}"
    public_ip_address: "{{ hostvars[item]['public_ip_address'] }}"
    public_dns_name: "{{ hostvars[item]['public_dns_name'] }}"
    private_ip_address: "{{ hostvars[item]['private_ip_address'] }}"
    private_dns_name: "{{ hostvars[item]['private_dns_name'] }}"
  with_items: groups[inventory_group_slave]