
- name: Add Appsoma user
  no_log: true
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    password: "{{item.password | password_hash('sha512') }}"
    groups: docker
    state: present
  with_items: user_list

- name: Add User's data dir
  file:
    name: "{{ dataDir }}/{{ item.username }}"
    owner: "{{ item.username }}"
    state: directory
  with_items: user_list

- name: Add ~/data link
  file:
    src: "{{ dataDir }}/{{ item.username }}"
    dest: "/home/{{ item.username }}/data"
    state: link
  with_items: user_list