
- name: Add Appsoma user
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    password: "{{item.passwd}}"
    groups: docker
    state: present
  with_items: user_list

- name: Add User's data dir
  file:
    name: "{{ dataDir }}/{{ item.username }}"
    owner: "{{ item.username }}"
    state: directory
  with_items: user_list

- name: Add ~/data link
  file:
    src: "{{ dataDir }}/{{ item.username }}"
    dest: "/home/{{ item.username }}/data"
    state: link
  with_items: user_list