
- name: Add Welder user group
  group:
    name: "{{ group['name'] }}"
    gid: "{{ group['gid'] }}"
    state: present

- name: Add Appsoma user
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    password: "{{item.password | password_hash('sha512') }}"
    group: "docker"
    groups: "{{ '' if item['test_group'] is defined else group['name'] }}"
    shell: "/bin/bash"
    state: present
  no_log: true
  with_items: user_list

- name: Add management user to Welder user group
  user: name="{{ management_user }}" groups="{{ welder_group['name'] }}" append=yes