
- name: Add Welder user group
  group:
    name: "{{ group['name'] }}"
    gid: "{{ group['gid'] }}"
    state: present

- name: Add Appsoma user
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    password: "{{item.password | password_hash('sha512') }}"
    group: "docker"
    groups: "{{ '' if item['test_group'] is defined else group['name'] }}"
    shell: "/bin/bash"
    state: present
  with_items: user_list

- name: Add User's data dir
  file:
    name: "{{ dataDir }}/{{ item.username }}"
    owner: "{{ item.username }}"
    group: "{{ group['name'] }}"
    state: directory
  with_items: user_list

- name: Add ~/data link
  file:
    src: "{{ dataDir }}/{{ item.username }}"
    dest: "/home/{{ item.username }}/data"
    state: link
  with_items: user_list