- name: Remove OS package if needed
  apt: name=maven state=absent force=yes

- name: Create Maven directory
  file: path=/opt/maven state=directory

- name: Get Maven binary tarball
  get_url:
    url: "http://apache.arvixe.com/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/opt/maven/apache-maven-{{ maven_version }}-bin.tar.gz"
  register: download_maven

- name: Expand Maven tareball
  command: tar -xzvf "/opt/maven/apache-maven-{{ maven_version }}-bin.tar.gz" -C /opt/maven/
  when: download_maven.changed

- name: Place Maven profile.d file
  template: src=maven.sh.j2 dest=/etc/profile.d/maven.sh
