- name: Install HAProxy (RedHat)
  yum: pkg=haproxy state=present
  when: ansible_os_family == "RedHat"

- name: Install HAProxy (Ubuntu)
  apt: pkg=haproxy state=present
  when: ansible_os_family == "Debian"

- name: Sets haproxy to enabled (Ubuntu)
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  when: ansible_os_family == "Debian"

- name: Create HAProxy start directory
  file: path=/opt/haproxy state=directory

- name: Get HAProxy bridge
  get_url:
    url: https://raw.githubusercontent.com/appsoma/devops/master/haproxy-marathon-bridge.py
    dest: /opt/haproxy//haproxy-marathon-bridge.py

- name: Create bridge config directory
  file: path=/etc/haproxy-marathon-bridge state=directory

- name: Create service configuration file
  template: src=service.json.j2 dest=/etc/haproxy-marathon-bridge/services.json
  when: haproxy_services is defined

- name: Create marathons configuration
  template: src=marathons.j2 dest=/etc/haproxy-marathon-bridge/marathons

- name: Create HAProxy cron job
  shell: "python /opt/haproxy/haproxy-marathon-bridge.py createCronJob"
  args:
    chdir: /opt/haproxy