- include: package.yml
  when: use_package and not use_source

- include: source.yml
  when: use_source and not use_package

- name: Create HAProxy start directory
  file: path=/opt/haproxy state=directory

- name: Get HAProxy bridge script and templates
  git:
    repo: "https://github.com/appsoma/gandalf.git"
    dest: "/opt/haproxy/gandalf"
    version: "{{ gandalf_version if gandalf_version is defined else 'HEAD' }}"
    update: yes

- name: Install Python Kazoo client
  command: /usr/bin/pip install kazoo

- name: Get zookeeper CLI
  get_url:
    url: https://github.com/outbrain/zookeepercli/releases/download/v1.0.10/zookeepercli_1.0.10_amd64.deb
    dest: /opt/haproxy/zookeepercli_1.0.10_amd64.deb
    force: yes

- name: Install zookeeper CLI
  apt: deb=/opt/haproxy/zookeepercli_1.0.10_amd64.deb state=present

- include: services.yml

- name: Create SSL certificate
  copy: src="cluster_vars/{{ cluster_name }}/haproxy.pem" dest=/opt/haproxy/haproxy.pem mode=600
  when: haproxy_use_ssl

- name: Create HAProxy cron job
  shell: "python /opt/haproxy/gandalf/gandalf.py --zookeeper {{ zookeeper_host_list }} install"
  args:
    chdir: /opt/haproxy/gandalf