welder_user: "ubuntu"
welder_port: 8890
welder_src_dir: "/opt/welder"
welder_etc_dir: "{{ appsoma_etc_dir }}/welder"
welder_log_dir: "{{ appsoma_log_dir }}"
welder_data_dir: "{{ data_mount_point }}/welder"
welder_support_dir: "{{ welder_data_dir }}/support"

# The following are what are emitted into the config file
# Because this yml file assumes that welder is running in a container
# the following are in container folder space
welder_config_data_dir: "/welderdata"
welder_config_projects_dir: "{{ welder_config_data_dir }}/projects"
welder_config_uploads_dir: "{{ welder_config_data_dir }}/uploads"
welder_config_support_dir: "{{ welder_config_data_dir }}/support"
welder_config_log_dir: "{{ welder_config_data_dir }}/log"

welder_db_type: "mongo"

welder_use_tls: false
use_container: true

external_welder_name: "{{ ext_ip }}:{{ welder_port }}"
external_welder_console_name: "{{ ext_ip }}"
int_welder_url: "{{ 'https' if welder_use_tls is defined and welder_use_tls else 'http' }}://master.mesos:{{welder_port }}"
ext_welder_url: "{{ 'https' if welder_use_tls is defined and welder_use_tls else 'http' }}://{{ external_welder_name }}"


db_folder: "{{ data_mount_point }}/welder_db"
db_host: "mongo.marathon.mesos"
db_port: 27017

marathon_host: "master.mesos"
scheduler_ip: "master.mesos"
zookeeper_hosts: "master.mesos:2181"
marathon_url: "http://{{ marathon_host }}:8080"

project_folder: "{{ welder_data_dir }}/projects"
upload_folder: "/{{ welder_data_dir }}/uploads"
service_log_folder: "{{ welder_data_dir }}/log"

scheduler: "rhino"
rhino_url: "http://{{ scheduler_ip }}:8899/"

use_https: False
key_path: "{{ welder_src_dir }}/certificate.key"
cert_path: "{{ welder_src_dir }}/certificate.crt"


