welder_user: "ubuntu"
welder_port: 8890
welder_dir: "/opt/welder"
welder_etc_dir: "{{ appsoma_etc_dir }}/welder"
welder_log_dir: "{{ appsoma_log_dir }}"

welder_use_tls: false
use_containers: false

int_welder_url: "{{ 'https' if welder_use_tls is defined and welder_use_tls else 'http' }}://{{ int_ip }}:{{welder_port }}"
ext_welder_url: "{{ 'https' if welder_use_tls is defined and welder_use_tls else 'http' }}://{{ ext_ip }}:{{ welder_port }}"

db_folder: "/mnt/data/welder_db"
db_host: "localhost"
db_port: 27017

marathon_host: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
marathon_url: "http://{{ marathon_host }}:8080"

project_folder: "{{ data_mount_point }}/welder/projects"
upload_folder: "/{{ data_mount_point }}/welder/uploads"
service_log_folder: "{{ data_mount_point }}/welder/projects"

scheduler: "rhino"
rhino_url: "http://{{ scheduler_ip }}:8899/"

use_https: False
key_path: "/opt/welder/certificate.key"
cert_path: "/opt/welder/certificate.crt"


