welder_user: "appsoma"
use_tls: false
use_containers: false
host_ip: "{{ inventory_hostname }}"

db_folder: "/mnt/data/welder_db"
db_port: 27107

project_folder: "/mnt/data/welder/projects"
upload_folder: "/mnt/data/welder/projects"

scheduler: "rhino"

use_https: False
pem_path: "~/mycert.pem"
cert_path: "~/mycert.crt"


