welder_user: "ubuntu"
welder_port: 8890
welder_log_dir: /var/log/appsoma
welder_use_tls: false
use_containers: false

db_folder: "/mnt/data/welder_db"
db_port: 27017

project_folder: "/mnt/data/welder/projects"
upload_folder: "/mnt/data/welder/uploads"

scheduler: "rhino"

use_https: False
key_path: "/opt/welder/certificate.key"
cert_path: "/opt/welder/certificate.crt"


