---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Install NTP (RedHat).
  yum: name=ntp state=installed
  when: ansible_os_family == 'RedHat' and package_install != 'False'

- name: Install NTP (Debian).
  apt: pkg=ntp state=installed
  when: ansible_os_family == 'Debian' and package_install != 'False'

- name: Ensure NTP is running and enabled at system start.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: no
  when: not ntp_enabled
