ansible_scaler_dir: "/opt/ansible-scaler"

terraform_version: "0.6.4"
terraform_cloud_provider:
  ec2: "terraform-provider-aws"
  gce: "terraform-provider-google"

terraform_executables:
  - terraform
  - "{{ terraform_cloud_provider[cloud_provider] }}"
  - terraform-provisioner-file
  - terraform-provisioner-remote-exec