ansible_scaler_dir: "{{ data_mount_point }}/ansible-scaler"
is_scaler_host: true
root_dir: ""

terraform_version: "0.6.10"
terraform_cloud_provider:
  ec2: "terraform-provider-aws"
  gce: "terraform-provider-google"

terraform_executables:
  - terraform
  - "{{ terraform_cloud_provider[cloud_provider] }}"
  - terraform-provisioner-file
  - terraform-provisioner-remote-exec