- name: Install collectd
  apt: pkg=collectd state=present
  notify: Restart collectd

- name: Make collect plugin directory
  file: path=/usr/share/collectd/plugins state=directory

- name: Get master plugin script
  get_url:
    url: https://raw.githubusercontent.com/rayrod2030/collectd-mesos/master/mesos-master.py
    dest: /usr/share/collectd/plugins/mesos-master.py
    force: yes
  when: mesos_mode == 'master' or mesos_mode == 'master-slave'
  notify: Restart collectd

- name: Put master plugin config file
  template: src=collectd_master_plugin.conf.j2 dest=/etc/collectd/collectd.conf.d/mesos-master.conf
  when: mesos_mode == 'master' or mesos_mode =='master-slave'
  notify: Restart collectd

- name: Copy slave plugin script
  get_url:
    url: https://raw.githubusercontent.com/rayrod2030/collectd-mesos/master/mesos-slave.py
    dest: /usr/share/collectd/plugins/mesos-slave.py
    force: yes
  when: mesos_mode == 'slave'
  notify: Restart collectd

- name: Put slave plugin config file
  template: src=collectd_slave_plugin.conf.j2 dest=/etc/collectd/collectd.conf.d/mesos-slave.conf
  when: mesos_mode == 'slave'
  notify: Restart collectd

- name: Copy the master config file
  template: src=collectd_master.conf.j2 dest=/etc/collectd/collectd.conf
  when: mesos_mode != 'slave'
  notify: Restart collectd

- name: Copy the slave config file
  template: src=collectd_slave.conf.j2 dest=/etc/collectd/collectd.conf
  when: mesos_mode == 'slave'
  notify: Restart collectd
