all_plugins:
  - sensu-plugins-cpu-checks
  - sensu-plugins-memory-checks
  - sensu-plugins-disk-checks
  - sensu-plugins-dns
  - sensu-plugins-ntp
  - sensu-plugins-influxdb

mesos_plugins:
  - sensu-plugins-mesos

master_plugins:
  - sensu-plugins-zookeeper
  - sensu-plugins-mongodb
  - sensu-plugins-haproxy

metric_interval: 60
check_interval: 30

sensu_mode: "client"
sensu_master: localhost
uchiwa_dir: "{{ data_mount_point }}/uchiwa"

uchiwa_docker_cmd: "sudo docker run -d --name uchiwa-dashboard --restart=always -p 18100:8100 -v {{ uchiwa_dir }}/config.json:/config/config.json uchiwa/uchiwa"

