- name: Format EBS disk volumes
  filesystem: fstype=ext4 dev="{{ item.device_name }}" force=yes
  with_items: "{{ additional_volume_list }}"

- name: Mount EBS disk volumes
  mount: name="{{ item.mount_point }}" src="{{ item.device_name }}" fstype=ext4 state=mounted
  with_items: "{{ additional_volume_list  }}"

- name: Change permissions for EBS disk volumes
  file: path="{{ item.mount_point }}" state=directory mode=0777 owner="{{ management_user }}"
  with_items: "{{ additional_volume_list }}"