
- name: Remove old local disk mounts
  mount: name="/mnt" src="{{ item.device_name }}" fstype=ext3 state=unmounted
  with_items: instance_store_list

- name: Format local disk volumes
  filesystem: fstype=ext4 dev="{{ item.device_name }}" force=yes
  with_items: instance_store_list

- name: Mount local disk volumes
  mount: name="{{ item.mount_point }}" src="{{ item.device_name }}" fstype=ext4 state=mounted
  with_items: instance_store_list

- name: Change permissions for local disk volumes
  file: path="{{ item.mount_point }}" state=directory mode=0777 owner="{{ management_user }}"
  with_items: instance_store_list

