- name: Check NAT rules
  shell: "iptables -n -t nat -L POSTROUTING | grep {{ nat_subnet }}/24 | grep 'MASQUERADE' "
  register: nat_rules
  changed_when: nat_rules.stdout == ""
  failed_when: nat_rules.stderr != ""

- name: Set NAT rules
  shell: "iptables -t nat -I POSTROUTING -o eth0 -s {{ nat_subnet }}/24 -j MASQUERADE"
  when: nat_rules.changed