- name: Install openvpn
  apt: pkg=openvpn state=present update_cache=yes

- name: Install easy-rsa
  apt: pkg=easy-rsa state=present update_cache=yes

- name: Allow IP forwarding
  lineinfile: dest=/proc/sys/net/ipv4/ip_forward regexp='^1' line='1'
  #shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Set IP forwarding in sysctl
  lineinfile: dest=/etc/sysctl.conf regexp='^net\.ipv4\.ip_forward=1' line='net.ipv4.ip_forward=1'

- name: Set IP masquerade rules


- name: Create VPN server config
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf mode=644

- name: Copy RSA generation scripts
  command: cp -r /usr/share/easy-rsa/ /etc/openvpn/
  args:
    creates: /etc/openvpn/easy-rsa/pkitool

- name: Set EasyRSA vars
  template: src=vars.j2 dest=/etc/openvpn/easy-rsa/vars

- name: Fix cleaner/prep script
  template: src=clean-all.j2 dest=/etc/openvpn/easy-rsa/clean-all

- name: Run cleaner/prep script
  shell: . ./vars && ./clean-all
  args:
    creates: /etc/openvpn/easy-rsa/keys/index.txt
    chdir: /etc/openvpn/easy-rsa

- name: Check for DH key
  file: path=/etc/openvpn/

- name: Create DH key
  shell: openssl dhparam -out /etc/openvpn/easy-rsa/keys/dh2048.pem 2048
  args:
    creates: /etc/openvpn/easy-rsa/keys/dh2048.pem
    chdir: /etc/openvpn/easy-rsa

- name: Build CA
  shell: . ./vars && ./pkitool --initca
  args:
    creates: /etc/openvpn/easy-rsa/keys/ca.crt
    chdir: /etc/openvpn/easy-rsa

- name: Fetch CA certificate
  fetch: src=/etc/openvpn/easy-rsa/keys/ca.crt dest=/tmp/ca.crt flat=yes fail_on_missing=yes

- name: Get CA certificate
  set_fact: ca_certificate="{{ lookup('file', '/tmp/ca.crt') }}"

- name: Build server certificate
  shell: . ./vars && ./pkitool --server server
  args:
    creates: /etc/openvpn/easy-rsa/keys/server.crt
    chdir: /etc/openvpn/easy-rsa

- name: Start server
  service: name=openvpn state=started enabled=yes

- name: Build client key
  shell: . ./vars && ./pkitool client1
  args:
    creates: /etc/openvpn/easy-rsa/keys/client1.key
    chdir: /etc/openvpn/easy-rsa

- name: Fetch client certificate
  fetch: src="/etc/openvpn/easy-rsa/keys/client1.crt" dest="/tmp/client1.crt" flat=yes fail_on_missing=yes

- name: Get client certificate
  set_fact: client_certificate="{{ lookup('file', '/tmp/client1.crt') }}"

- name: Fetch client key
  fetch: src="/etc/openvpn/easy-rsa/keys/client1.key" dest="/tmp/client1.key" flat=yes fail_on_missing=yes

- name: Get client key
  set_fact: client_key="{{ lookup('file', '/tmp/client1.key') }}"

- name: Build client ovpn config
  template: src=client.ovpn.j2 dest=/etc/openvpn/client.ovpn
