cluster_name: "test"
data_mount_point: "/mnt/data/"
data_vol_size_gb: 250
data_vol_type: "standard"

cloud_provider: ec2
#cloud_provider: gce
#cloud_provider: azure

# Amazon EC2
ec2_region: "us-east-1"
ec2_zone: "us-east-1a"
ec2_ami_id: "ami-7eb2a716" # Base HVM Ubuntu 14.04 image


master_instance_type: "t2.micro"
service_instance_type: "t2.micro"
slave_instance_type: "t2.medium"

# Network settings
private_lan_net: "10.10.0.0/16"
private_lan_subnet: "10.10.0.0/24"

# NFS Data options
data_mount_point: "/mnt/data"
data_vol_size_gb: 100
data_vol_type: "standard"