- name: Make Mesos-DNS dir
  file: path="{{ mesos_dns_dir }}" state=directory owner="{{ management_user }}"

- name: Install Mesos-DNS config
  template: src=config.json.j2 dest="{{ mesos_dns_dir }}/config.json" owner="{{ management_user }}"

- name: Install Mesos-DNS marathon json
  template: src=mesos_dns_marathon.json.j2 dest="{{ mesos_dns_dir }}/mesos_dns_marathon.json" owner="{{ management_user }}"

- name: Install Mesos-DNS start script
  template: src=run_mesos_dns.sh.j2 dest="{{ mesos_dns_dir }}/run_mesos_dns.sh" owner="{{ management_user }}" mode=700

- name: Start Mesos-DNS in Marathon
  shell: "{{ mesos_dns_dir }}/run_mesos_dns.sh start"
  register: start_mesos_dns
  changed_when: start_mesos_dns.stderr == "" or start_mesos_dns.stderr.find('already in use') == -1
  failed_when: start_mesos_dns.stderr != "" and start_mesos_dns.stderr.find('already in use') == -1 and start_mesos_dns.stderr.find('Downloaded newer image') == -1

- name: Debug Mesos-DNS start
  debug: var=start_mesos_dns