- include: install.yml
  when: is_mesos_dns_starter

- name: Add Mesos-DNS as nameserver
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/head line="nameserver {{ item }}"
  with_items: mesos_dns_hosts

- name: Add "mesos" domain search
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/base line="search mesos"

- name: Refresh resolv.conf
  command: resolvconf -u

