- include: install.yml
  when: is_mesos_dns_starter

- name: Add Mesos-DNS as nameserver
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/head line="nameserver {{ item }}" regexp="^nameserver "
  register: add_ns
  with_items: mesos_dns_hosts

- name: Add "mesos" domain search
  lineinfile: dest=/etc/resolvconf/resolv.conf.d/base line="search mesos"

- name: Check for mesos in resolv.conf
  shell: "grep mesos /etc/resolv.conf | wc -l"
  register: resolv_conf
  changed_when: resolv_conf.stdout != '1'

- name: Refresh resolv.conf
  command: resolvconf -u
  when: resolv_conf.changed or add_ns.changed

