- name: install nfs client
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nfs-common
    - rpcbind
  when: ansible_os_family == "Debian" and package_install != 'False'

- name: install nfs client
  yum: pkg={{ item }} state=present
  with_items:
    - nfs-utils
    - rpcbind
  when: ansible_os_family == "RedHat" and package_install != 'False'

- name: Ensure portmap is running (Ubuntu prior to Trusty Thar)
  service: name=portmap state=started enabled=yes
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release is defined and ansible_lsb.major_release|int < 14

- name: Ensure rpcbind is running (Ubuntu Trusty Tahr or newer)
  service: name=rpcbind state=started enabled=yes
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release is defined and ansible_lsb.major_release|int >= 14

- name: Ensure rpcbind is running (Debian)
  service: name=rpcbind state=started enabled=yes
  when: ansible_distribution == "Debian"

- name: Ensure {{nfsmount}} directory exists
  file: path={{nfsmount}} state=directory
  when: nfsmount is defined

- name: configure /etc/fstab on clients
  mount: name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts="{{ mount_options }}" state=mounted
  when: nfsmount is defined and nfsserver is defined and nfspath is defined