---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present
  when: package_install

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present update_cache=yes
  when: package_install

- name: Install Debian OS packages
  apt: pkg={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - mesos={{mesos_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
  when: package_install

# == Remove zookeeper daemon which shouldn't be running on slaves
- name: Remove zookeeperd from slaves
  apt: pkg=zookeeperd state=absent
  when: mesos_install_mode == "slave" and package_install

- name: Fix rsyslog service
  file: path=/etc/init.d/rsyslog state=absent

- name: Fix logrotate to use smaller syslog files
  template: src=rsyslog.rotate.j2 dest=/etc/logrotate.d/rsyslog
  notify: Restart rsyslog

- name: Fix Syslog to use separate files for mesos and marathon
  template: src=syslog_mesos.conf.j2 dest=/etc/rsyslog.d/mesos.conf
  notify: Restart rsyslog

- name: Fix logrotate to rotate mesos files
  template: src=mesos.rotate.j2 dest=/etc/logrotate.d/mesos
  notify: Restart rsyslog

- name: Add cron to restart rsyslog twice a day
  lineinfile: dest=/etc/cron.d/rsyslog line="0 0,12 * * * root service rsyslog restart" state=present create=yes
