---
# == Work Dir for replicated log
- name: create work dir
  file: path=/var/mesos state=directory

# == Remove default master config on slaves
- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/
  when: mesos_install_mode == "slave"

# == Configure and recreate
- name: Make Mesos dir
  file: path=/etc/mesos state=directory

- name: Set Mesos ZK File
  template: src=zk.j2 dest=/etc/mesos/zk
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Set Mesos Work Dir File
  template: src=work_dir.j2 dest=/etc/mesos-master/work_dir
  notify:
    - Restart mesos-master
  when: mesos_install_mode == "master"

- name: Set Mesos Work Dir File
  template: src=work_dir.j2 dest=/etc/mesos-slave/work_dir
  notify:
    - Restart mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Set Mesos Resources File
  template: src=slave_resources.j2 dest=/etc/mesos-slave/resources
  notify:
    - Restart mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos master script
  template: src=init-mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos slave script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Start and enable mesos-master
  service: name=mesos-master state=started
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Start and enable mesos-slave
  service: name=mesos-slave state=started
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
