---
- name: Install os packages
  apt: pkg={{item}} state=present
  with_items: 
    - build-essential
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - wget
    - python2.7
    - python3.4
    - python-pip

