---
- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  tags: bootstrap
  with_items:
    - zookeeper
    - zookeeperd
  notify:
    - Restart Zookeeper

- name: Overwrite myid file.
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid
  tags: deploy
  notify:
    - Restart Zookeeper

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  tags: deploy
  notify:
    - Restart Zookeeper

