- name: Add Go PPA repo key
  apt_key: keyserver="keyserver.ubuntu.com" id="742A38EE"

- name: Add Go PPA repo
  apt_repository: repo="deb http://ppa.launchpad.net/evarlast/golang1.4/ubuntu trusty main" update_cache=yes state=present

- name: Install Go
  apt: pkg=golang state=present update_cache=yes