#- name: Add Go PPA repo key
#  apt_key: keyserver="keyserver.ubuntu.com" id="742A38EE"

- name: Add Go PPA repo
  apt_repository: repo="ppa:ubuntu-lxc/lxd-stable" update_cache=yes state=present

- name: Install Go
  apt: pkg=golang state=present