- name: Create VPC
  ec2_vpc:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    internet_gateway: yes
    region: "{{ ec2_region }}"
    cidr_block: "{{private_lan_net}}"
    resource_tags: { "Name": "mesos-{{ cluster_name }}" }
    subnets:
      - cidr: "{{private_lan_subnet}}"
        az: "{{ ec2_zone }}"
        resource_tags: { "Name": "mesos-{{ cluster_name }}", "subnet_id": "base" }
    route_tables:
      - subnets:
          - "{{private_lan_subnet}}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    state: present
    wait: yes
  register: vpc

- name: Set VPC ID
  set_fact: aws_vpc_id="{{ vpc['vpc_id'] }}"

- name: Set Subnet ID
  set_fact: aws_vpc_subnet_id="{{ vpc['subnets'][0]['id']}}"

- debug: msg="{{aws_vpc_id}} {{aws_vpc_subnet_id}}"

- name: Create Security Group
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ aws_vpc_id }}"
    name: "mesos-{{ cluster_name }}-sg"
    description: "Security group for cluster {{ cluster_name }}"
    rules:
      - proto: all
        group_name: "mesos-{{ cluster_name }}-sg"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5050
        to_port: 5050
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8088
        to_port: 8088
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8089
        to_port: 8089
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8888
        to_port: 8888
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 10090
        to_port: 10090
        cidr_ip: 0.0.0.0/0
  register: securityGroup

- set_fact: aws_security_group_id="{{ securityGroup['group_id'] }}"
- debug: msg=" GRP {{ aws_security_group_id }}"




