is_mesos_dns_starter: false
mesos_dns_dir: "{{ data_mount_point }}/mesos_dns"
mesos_dns_docker_cmd: "docker run -d --name mesos-dns --restart=always -p 53:53/udp -p 5001:5001 -v {{ mesos_dns_dir }}/config.json:/config.json mesosphere/mesos-dns /mesos-dns -v 2 -config=config.json"
