---
- hosts: localhost
  connection: local
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    # Create a VPC
    - role: ec2Vpc
      when: "aws_all_security_group_id is not defined"

    # Boot the NFS server node
    - role: ec2Boot
      count: 1
      node_class: "{{service_class_name}}"
      node_group_name: "{{ inventory_group_service }}"
