---
# Creates "master_count" mesos master nodes and adds to the hosts file, as well as the dynamic inventory in group mesos_master
- hosts: localhost
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  tasks:

    - name: Add service node variables to host list
      add_host:
        hostname: "{{ hostvars[item]['ec2_ip_address'] }}"
        groupname: "{{ inventory_group_service }}"
        system_name: "{{ hostvars[item]['ec2_tag_Name'] }}"
        id: "{{ hostvars[item]['ec2_tag_id'] }}"
        public_ip_address: "{{ hostvars[item]['ec2_ip_address'] }}"
        public_dns_name: "{{ hostvars[item]['ec2_public_dns_name'] }}"
        private_ip_address: "{{ hostvars[item]['ec2_private_ip_address'] }}"
        private_dns_name: "{{ hostvars[item]['ec2_private_dns_name'] }}"
      with_items: groups[inventory_group_service]

    - name: Add master node variables to host list
      add_host:
        hostname: "{{ hostvars[item]['ec2_ip_address'] }}"
        groupname: "{{ inventory_group_master }}"
        system_name: "{{ hostvars[item]['ec2_tag_Name'] }}"
        id: "{{ hostvars[item]['ec2_tag_id'] }}"
        zoo_id: "{{ hostvars[item]['ec2_tag_zoo_id'] }}"
        public_ip_address: "{{ hostvars[item]['ec2_ip_address'] }}"
        public_dns_name: "{{ hostvars[item]['ec2_public_dns_name'] }}"
        private_ip_address: "{{ hostvars[item]['ec2_private_ip_address'] }}"
        private_dns_name: "{{ hostvars[item]['ec2_private_dns_name'] }}"
      with_items: groups[inventory_group_master]

    - name: Add slave node variables to host list
      add_host:
        hostname: "{{ hostvars[item]['ec2_ip_address'] }}"
        groupname: "{{ inventory_group_slave }}"
        system_name: "{{ hostvars[item]['ec2_tag_Name'] }}"
        id: "{{ hostvars[item]['ec2_tag_id'] }}"
        public_ip_address: "{{ hostvars[item]['ec2_ip_address'] }}"
        public_dns_name: "{{ hostvars[item]['ec2_public_dns_name'] }}"
        private_ip_address: "{{ hostvars[item]['ec2_private_ip_address'] }}"
        private_dns_name: "{{ hostvars[item]['ec2_private_dns_name'] }}"
      with_items: groups[inventory_group_slave]