---
- hosts: localhost
  connection: local
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    - role: ../roles/ansible-cloud-inventory-parse
      provider: "{{ cloud_provider }}"

- hosts: [ "{{ inventory_group_master }}" ]

  remote_user: "{{ management_user }}"
  become: yes
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/users.yml"

  pre_tasks:
    - name: Set master_0 hostname
      set_fact: master_0_hostname="{{ item }}"
      with_items: "{{ groups[inventory_group_master] }}"
      when: hostvars[ item ].short_name == "master_0"

  roles:
    - role: ../roles/ansible-haProxy
      haproxy_pem_file: "../cluster_vars/{{ cluster_name }}/haproxy.pem"
      when: inventory_hostname == master_0_hostname