---
- hosts: localhost
  connection: local
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  tasks:
    - name: Select Cloud Provider if needed
      debug: msg="Provider == {{ cloud_provider }}"
- include: ../playbooks/ec2_inventory_parse.yml
  when: cloud_provider == "ec2"

- hosts: [ "{{ inventory_group_master }}" ]

  remote_user: "{{ management_user }}"
  sudo: True
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/users.yml"

  pre_tasks:
    - name: Set zookeeper private IP list with port
      set_fact:
        zookeeper_hosts_with_port: |
          {% set comma = joiner(':' + zookeeper_client_port + ',') %}
          {% for item in groups[inventory_group_master] -%}
            {{ comma() }}{{ hostvars[item].private_ip_address }}:{{ zookeeper_client_port }}
          {%- endfor %}
  roles:
    - role: ../roles/ansible-haProxy
      zookeeper_host_list: "{{zookeeper_hosts_with_port}}"
      haproxy_pem_file: "../cluster_vars/{{ cluster_name }}/haproxy.pem"