---
- hosts: localhost
  connection: local
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    - role: ../roles/ansible-cloud-inventory-parse
      provider: "{{ cloud_provider }}"

- hosts: [ "{{ inventory_group_master }}" ]
  remote_user: "{{ management_user }}"
  become: yes
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/users.yml"

  pre_tasks:
    - name:  Set zookeeper private IP list with port
      set_fact:
        zookeeper_hosts_with_port: |
          {% set comma = joiner(':' + zookeeper_client_port + ',') %}
          {% for item in groups[inventory_group_master] -%}
            {{ comma() }}{{ hostvars[item].private_ip_address }}:{{ zookeeper_client_port }}
          {%- endfor %}

    - name:  Set zookeeper private IP list
      set_fact:
        zookeeper_hosts_no_port: |
          {% set comma = joiner(',') %}
          {% for item in groups[inventory_group_master] -%}
            {{ comma() }}{{ hostvars[item].private_ip_address }}
          {%- endfor %}

    - name: Set master_0 hostname
      set_fact: master_0_hostname="{{ item }}"
      with_items: "{{ groups[inventory_group_master] }}"
      when: hostvars[ item ].short_name == "master_0"

  roles:
    - role: ../roles/ansible-kafka-mesos
      zookeeper_hosts: "{{ zookeeper_hosts_with_port }}"
      zookeeper_hosts_no_port_list: "{{ zookeeper_hosts_no_port.split(',') }}"
      when: inventory_hostname == master_0_hostname