---
- hosts: [ "{{ inventory_group_service }}" ]
  remote_user: ubuntu
  sudo: True
  vars_files:
    - ../playbook_vars/common.yml
    - ../playbook_vars/required_vars.yml
    - ../playbook_vars/users.yml

  roles:
    # Install Python
    - role: ../roles/ansible-python
      when: inventory_hostname == groups[inventory_group_service][0]
      
    # Install NodeJs
    - role: ../roles/ansible-nvm-nodejs
      nodejs_version: "v0.12.4"
      nodejs_global_packages:
        - browserify
        - mocha
        - nodejs-websocket
        - phantomjs
        - process
        - require
        - scribe-js
        - supervisor
      tags: ["nodejs"]
      when: inventory_hostname == groups[inventory_group_service][0]

    - role: ../roles/ansible-welder
      int_ip: "{{ hostvars[inventory_hostname]['ec2_private_ip_address'] }}"
      ext_ip: "{{ hostvars[inventory_hostname]['ec2_ip_address'] }}"
      scheduler_ip: "{{ hostvars[groups[inventory_group_master][0]]['ec2_private_ip_address'] }}"
      db_folder: "{{ nfs_data_mount }}/welder_test_db"
      project_folder: "{{ nfs_data_mount }}/welder_test/projects"
      upload_folder: "{{ nfs_data_mount }}/welder_test/uploads"
      scheduler: "rhino"
      welder_branch: "{{ welder_test_branch if welder_test_branch is defined else 'HEAD' }}"
      when: inventory_hostname == groups[inventory_group_service][0]