---
- hosts: localhost
  connection: local
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/aws_secret_vars.yml"
  roles:
    - role: ../roles/ansible-cloud-inventory-parse
      provider: "{{ cloud_provider }}"

- hosts: [ "{{ inventory_group_master }}" ]
  remote_user: "{{ management_user }}"
  sudo: True
  vars_files:
    - "../cluster_vars/common.yml"
    - "../cluster_vars/{{ cluster_name }}/required_vars.yml"
    - "../cluster_vars/{{ cluster_name }}/users.yml"
  pre_tasks:
    - name: Check for version to use
      debug: msg="Using version {{ welder_version if welder_version is defined else 'HEAD' }}"

    - name: Create Appsoma etc directory
      file: path="{{ appsoma_etc_dir }}" state=directory

    - name: Create Appsoma cluster_id file
      lineinfile: dest="{{ appsoma_etc_dir }}/cluster_id" create=yes line="{{ cluster_name }}" state=present

    - name: Create Appsoma log directory
      file: path="{{ appsoma_etc_dir }}" state=directory

    - name: Set zookeeper private IP list with port
      set_fact:
        zookeeper_hosts_with_port: |
          {% set comma = joiner(':' + zookeeper_client_port + ',') %}
          {% for item in groups[inventory_group_master] -%}
            {{ comma() }}{{ hostvars[item].private_ip_address }}:{{ zookeeper_client_port }}
          {%- endfor %}

  roles:
    - role: ../roles/ansible-welder
      int_ip: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
      ext_ip: "{{ hostvars[inventory_hostname]['public_ip_address'] }}"
      scheduler_ip: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
      marathon_host: "{{ hostvars[inventory_hostname]['private_ip_address'] }}"
      zookeeper_hosts: "{{ zookeeper_hosts_with_port }}"
      scheduler: "rhino"
      when: inventory_hostname == groups[inventory_group_master][0]